spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hw1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://mysql:3306/hw1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: llt123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    com.AdminMange.dao: debug