spring:
  redis:
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
    host: ${REDIS_HOST:127.0.0.1}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hw1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://mysql:3306/hw1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: llt123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    com.AdminMange.dao: debug

server:
  port: 8081


