spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: llt123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    sql:
      init:
        mode: always
dubbo:
  application:
    name: Group14-user-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20883
logging:
  level:
    root: info
    com.AdminMange.dao: debug
server:
  port: 7002